// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: project.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectGrpcService_GetUserProjects_FullMethodName         = "/project.ProjectGrpcService/GetUserProjects"
	ProjectGrpcService_GetProjectBoard_FullMethodName         = "/project.ProjectGrpcService/GetProjectBoard"
	ProjectGrpcService_GetProjectTaskBlueprint_FullMethodName = "/project.ProjectGrpcService/GetProjectTaskBlueprint"
	ProjectGrpcService_CreateTask_FullMethodName              = "/project.ProjectGrpcService/CreateTask"
	ProjectGrpcService_CreateColumn_FullMethodName            = "/project.ProjectGrpcService/CreateColumn"
	ProjectGrpcService_SubscribeAIEvents_FullMethodName       = "/project.ProjectGrpcService/SubscribeAIEvents"
	ProjectGrpcService_SendAIChatResponse_FullMethodName      = "/project.ProjectGrpcService/SendAIChatResponse"
)

// ProjectGrpcServiceClient is the client API for ProjectGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectGrpcServiceClient interface {
	// Get all projects for a specific user
	GetUserProjects(ctx context.Context, in *UserProjectsRequest, opts ...grpc.CallOption) (*UserProjectsResponse, error)
	// Get project board (columns and tasks)
	GetProjectBoard(ctx context.Context, in *ProjectBoardRequest, opts ...grpc.CallOption) (*ProjectBoardResponse, error)
	// Get task creation blueprint (valid columns, tags, priority, current time)
	GetProjectTaskBlueprint(ctx context.Context, in *TaskBlueprintRequest, opts ...grpc.CallOption) (*TaskBlueprintResponse, error)
	// Create a new task
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	// Create a new column
	CreateColumn(ctx context.Context, in *CreateColumnRequest, opts ...grpc.CallOption) (*CreateColumnResponse, error)
	// AI microservice calls this once to subscribe to AI chat events.
	// Java streams AIEvent messages whenever a user sends an AI chat message.
	SubscribeAIEvents(ctx context.Context, in *AIEventSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AIEvent], error)
	SendAIChatResponse(ctx context.Context, in *AIEvent, opts ...grpc.CallOption) (*SendAIChatResponseResponse, error)
}

type projectGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectGrpcServiceClient(cc grpc.ClientConnInterface) ProjectGrpcServiceClient {
	return &projectGrpcServiceClient{cc}
}

func (c *projectGrpcServiceClient) GetUserProjects(ctx context.Context, in *UserProjectsRequest, opts ...grpc.CallOption) (*UserProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProjectsResponse)
	err := c.cc.Invoke(ctx, ProjectGrpcService_GetUserProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectGrpcServiceClient) GetProjectBoard(ctx context.Context, in *ProjectBoardRequest, opts ...grpc.CallOption) (*ProjectBoardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectBoardResponse)
	err := c.cc.Invoke(ctx, ProjectGrpcService_GetProjectBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectGrpcServiceClient) GetProjectTaskBlueprint(ctx context.Context, in *TaskBlueprintRequest, opts ...grpc.CallOption) (*TaskBlueprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskBlueprintResponse)
	err := c.cc.Invoke(ctx, ProjectGrpcService_GetProjectTaskBlueprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectGrpcServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, ProjectGrpcService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectGrpcServiceClient) CreateColumn(ctx context.Context, in *CreateColumnRequest, opts ...grpc.CallOption) (*CreateColumnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateColumnResponse)
	err := c.cc.Invoke(ctx, ProjectGrpcService_CreateColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectGrpcServiceClient) SubscribeAIEvents(ctx context.Context, in *AIEventSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AIEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProjectGrpcService_ServiceDesc.Streams[0], ProjectGrpcService_SubscribeAIEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AIEventSubscribeRequest, AIEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectGrpcService_SubscribeAIEventsClient = grpc.ServerStreamingClient[AIEvent]

func (c *projectGrpcServiceClient) SendAIChatResponse(ctx context.Context, in *AIEvent, opts ...grpc.CallOption) (*SendAIChatResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendAIChatResponseResponse)
	err := c.cc.Invoke(ctx, ProjectGrpcService_SendAIChatResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectGrpcServiceServer is the server API for ProjectGrpcService service.
// All implementations must embed UnimplementedProjectGrpcServiceServer
// for forward compatibility.
type ProjectGrpcServiceServer interface {
	// Get all projects for a specific user
	GetUserProjects(context.Context, *UserProjectsRequest) (*UserProjectsResponse, error)
	// Get project board (columns and tasks)
	GetProjectBoard(context.Context, *ProjectBoardRequest) (*ProjectBoardResponse, error)
	// Get task creation blueprint (valid columns, tags, priority, current time)
	GetProjectTaskBlueprint(context.Context, *TaskBlueprintRequest) (*TaskBlueprintResponse, error)
	// Create a new task
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	// Create a new column
	CreateColumn(context.Context, *CreateColumnRequest) (*CreateColumnResponse, error)
	// AI microservice calls this once to subscribe to AI chat events.
	// Java streams AIEvent messages whenever a user sends an AI chat message.
	SubscribeAIEvents(*AIEventSubscribeRequest, grpc.ServerStreamingServer[AIEvent]) error
	SendAIChatResponse(context.Context, *AIEvent) (*SendAIChatResponseResponse, error)
	mustEmbedUnimplementedProjectGrpcServiceServer()
}

// UnimplementedProjectGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectGrpcServiceServer struct{}

func (UnimplementedProjectGrpcServiceServer) GetUserProjects(context.Context, *UserProjectsRequest) (*UserProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProjects not implemented")
}
func (UnimplementedProjectGrpcServiceServer) GetProjectBoard(context.Context, *ProjectBoardRequest) (*ProjectBoardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectBoard not implemented")
}
func (UnimplementedProjectGrpcServiceServer) GetProjectTaskBlueprint(context.Context, *TaskBlueprintRequest) (*TaskBlueprintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectTaskBlueprint not implemented")
}
func (UnimplementedProjectGrpcServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedProjectGrpcServiceServer) CreateColumn(context.Context, *CreateColumnRequest) (*CreateColumnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateColumn not implemented")
}
func (UnimplementedProjectGrpcServiceServer) SubscribeAIEvents(*AIEventSubscribeRequest, grpc.ServerStreamingServer[AIEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeAIEvents not implemented")
}
func (UnimplementedProjectGrpcServiceServer) SendAIChatResponse(context.Context, *AIEvent) (*SendAIChatResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAIChatResponse not implemented")
}
func (UnimplementedProjectGrpcServiceServer) mustEmbedUnimplementedProjectGrpcServiceServer() {}
func (UnimplementedProjectGrpcServiceServer) testEmbeddedByValue()                            {}

// UnsafeProjectGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectGrpcServiceServer will
// result in compilation errors.
type UnsafeProjectGrpcServiceServer interface {
	mustEmbedUnimplementedProjectGrpcServiceServer()
}

func RegisterProjectGrpcServiceServer(s grpc.ServiceRegistrar, srv ProjectGrpcServiceServer) {
	// If the following call panics, it indicates UnimplementedProjectGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectGrpcService_ServiceDesc, srv)
}

func _ProjectGrpcService_GetUserProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectGrpcServiceServer).GetUserProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectGrpcService_GetUserProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectGrpcServiceServer).GetUserProjects(ctx, req.(*UserProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectGrpcService_GetProjectBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectGrpcServiceServer).GetProjectBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectGrpcService_GetProjectBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectGrpcServiceServer).GetProjectBoard(ctx, req.(*ProjectBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectGrpcService_GetProjectTaskBlueprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskBlueprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectGrpcServiceServer).GetProjectTaskBlueprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectGrpcService_GetProjectTaskBlueprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectGrpcServiceServer).GetProjectTaskBlueprint(ctx, req.(*TaskBlueprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectGrpcService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectGrpcServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectGrpcService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectGrpcServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectGrpcService_CreateColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectGrpcServiceServer).CreateColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectGrpcService_CreateColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectGrpcServiceServer).CreateColumn(ctx, req.(*CreateColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectGrpcService_SubscribeAIEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AIEventSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProjectGrpcServiceServer).SubscribeAIEvents(m, &grpc.GenericServerStream[AIEventSubscribeRequest, AIEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectGrpcService_SubscribeAIEventsServer = grpc.ServerStreamingServer[AIEvent]

func _ProjectGrpcService_SendAIChatResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectGrpcServiceServer).SendAIChatResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectGrpcService_SendAIChatResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectGrpcServiceServer).SendAIChatResponse(ctx, req.(*AIEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectGrpcService_ServiceDesc is the grpc.ServiceDesc for ProjectGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "project.ProjectGrpcService",
	HandlerType: (*ProjectGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserProjects",
			Handler:    _ProjectGrpcService_GetUserProjects_Handler,
		},
		{
			MethodName: "GetProjectBoard",
			Handler:    _ProjectGrpcService_GetProjectBoard_Handler,
		},
		{
			MethodName: "GetProjectTaskBlueprint",
			Handler:    _ProjectGrpcService_GetProjectTaskBlueprint_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _ProjectGrpcService_CreateTask_Handler,
		},
		{
			MethodName: "CreateColumn",
			Handler:    _ProjectGrpcService_CreateColumn_Handler,
		},
		{
			MethodName: "SendAIChatResponse",
			Handler:    _ProjectGrpcService_SendAIChatResponse_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeAIEvents",
			Handler:       _ProjectGrpcService_SubscribeAIEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "project.proto",
}
