// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: project.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Project) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Priority      string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Order         string                 `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	ColumnId      string                 `protobuf:"bytes,5,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Deadline      string                 `protobuf:"bytes,7,opt,name=deadline,proto3" json:"deadline,omitempty"` // ISO-8601 string
	Tags          []*Tag                 `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Task) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Task) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

func (x *Task) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Task) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *Task) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Position      string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,5,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{3}
}

func (x *Column) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Column) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Column) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type UserProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProjectsRequest) Reset() {
	*x = UserProjectsRequest{}
	mi := &file_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProjectsRequest) ProtoMessage() {}

func (x *UserProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProjectsRequest.ProtoReflect.Descriptor instead.
func (*UserProjectsRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{4}
}

func (x *UserProjectsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProjectsResponse) Reset() {
	*x = UserProjectsResponse{}
	mi := &file_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProjectsResponse) ProtoMessage() {}

func (x *UserProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProjectsResponse.ProtoReflect.Descriptor instead.
func (*UserProjectsResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{5}
}

func (x *UserProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type ProjectBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectBoardRequest) Reset() {
	*x = ProjectBoardRequest{}
	mi := &file_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectBoardRequest) ProtoMessage() {}

func (x *ProjectBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectBoardRequest.ProtoReflect.Descriptor instead.
func (*ProjectBoardRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectBoardRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ProjectBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Columns       []*Column              `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectBoardResponse) Reset() {
	*x = ProjectBoardResponse{}
	mi := &file_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectBoardResponse) ProtoMessage() {}

func (x *ProjectBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectBoardResponse.ProtoReflect.Descriptor instead.
func (*ProjectBoardResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectBoardResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProjectBoardResponse) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

type TaskBlueprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskBlueprintRequest) Reset() {
	*x = TaskBlueprintRequest{}
	mi := &file_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskBlueprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskBlueprintRequest) ProtoMessage() {}

func (x *TaskBlueprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskBlueprintRequest.ProtoReflect.Descriptor instead.
func (*TaskBlueprintRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{8}
}

func (x *TaskBlueprintRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type TaskBlueprintResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TagOptions      []*TagOption           `protobuf:"bytes,3,rep,name=tag_options,json=tagOptions,proto3" json:"tag_options,omitempty"`
	ColumnOptions   []*ColumnOption        `protobuf:"bytes,4,rep,name=column_options,json=columnOptions,proto3" json:"column_options,omitempty"`
	PriorityOptions []*PriorityOption      `protobuf:"bytes,5,rep,name=priority_options,json=priorityOptions,proto3" json:"priority_options,omitempty"`
	CurrentDateTime string                 `protobuf:"bytes,6,opt,name=current_date_time,json=currentDateTime,proto3" json:"current_date_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskBlueprintResponse) Reset() {
	*x = TaskBlueprintResponse{}
	mi := &file_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskBlueprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskBlueprintResponse) ProtoMessage() {}

func (x *TaskBlueprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskBlueprintResponse.ProtoReflect.Descriptor instead.
func (*TaskBlueprintResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{9}
}

func (x *TaskBlueprintResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskBlueprintResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskBlueprintResponse) GetTagOptions() []*TagOption {
	if x != nil {
		return x.TagOptions
	}
	return nil
}

func (x *TaskBlueprintResponse) GetColumnOptions() []*ColumnOption {
	if x != nil {
		return x.ColumnOptions
	}
	return nil
}

func (x *TaskBlueprintResponse) GetPriorityOptions() []*PriorityOption {
	if x != nil {
		return x.PriorityOptions
	}
	return nil
}

func (x *TaskBlueprintResponse) GetCurrentDateTime() string {
	if x != nil {
		return x.CurrentDateTime
	}
	return ""
}

type TagOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagOption) Reset() {
	*x = TagOption{}
	mi := &file_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagOption) ProtoMessage() {}

func (x *TagOption) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagOption.ProtoReflect.Descriptor instead.
func (*TagOption) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{10}
}

func (x *TagOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagOption) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type ColumnOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnOption) Reset() {
	*x = ColumnOption{}
	mi := &file_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnOption) ProtoMessage() {}

func (x *ColumnOption) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnOption.ProtoReflect.Descriptor instead.
func (*ColumnOption) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{11}
}

func (x *ColumnOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ColumnOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnOption) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type PriorityOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priority      string                 `protobuf:"bytes,1,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorityOption) Reset() {
	*x = PriorityOption{}
	mi := &file_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityOption) ProtoMessage() {}

func (x *PriorityOption) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityOption.ProtoReflect.Descriptor instead.
func (*PriorityOption) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{12}
}

func (x *PriorityOption) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ColumnId      string                 `protobuf:"bytes,2,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Deadline      string                 `protobuf:"bytes,6,opt,name=deadline,proto3" json:"deadline,omitempty"` // ISO-8601 string
	Priority      string                 `protobuf:"bytes,7,opt,name=priority,proto3" json:"priority,omitempty"`
	TagIds        []string               `protobuf:"bytes,8,rep,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTaskRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateTaskRequest) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateTaskRequest) GetTagIds() []string {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Priority      string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Order         string                 `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	ColumnId      string                 `protobuf:"bytes,5,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Deadline      string                 `protobuf:"bytes,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Tags          []*Tag                 `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{14}
}

func (x *CreateTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTaskResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskResponse) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateTaskResponse) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *CreateTaskResponse) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

func (x *CreateTaskResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateTaskResponse) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *CreateTaskResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateColumnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateColumnRequest) Reset() {
	*x = CreateColumnRequest{}
	mi := &file_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColumnRequest) ProtoMessage() {}

func (x *CreateColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColumnRequest.ProtoReflect.Descriptor instead.
func (*CreateColumnRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{15}
}

func (x *CreateColumnRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateColumnRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateColumnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Position      string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateColumnResponse) Reset() {
	*x = CreateColumnResponse{}
	mi := &file_project_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateColumnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColumnResponse) ProtoMessage() {}

func (x *CreateColumnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColumnResponse.ProtoReflect.Descriptor instead.
func (*CreateColumnResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{16}
}

func (x *CreateColumnResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateColumnResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateColumnResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateColumnResponse) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

var File_project_proto protoreflect.FileDescriptor

const file_project_proto_rawDesc = "" +
	"\n" +
	"\rproject.proto\x12\aproject\"\x87\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\tR\agroupId\"?\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"\xd5\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x12\x14\n" +
	"\x05order\x18\x04 \x01(\tR\x05order\x12\x1b\n" +
	"\tcolumn_id\x18\x05 \x01(\tR\bcolumnId\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1a\n" +
	"\bdeadline\x18\a \x01(\tR\bdeadline\x12 \n" +
	"\x04tags\x18\b \x03(\v2\f.project.TagR\x04tags\"\x83\x01\n" +
	"\x06Column\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\x12#\n" +
	"\x05tasks\x18\x05 \x03(\v2\r.project.TaskR\x05tasks\".\n" +
	"\x13UserProjectsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"D\n" +
	"\x14UserProjectsResponse\x12,\n" +
	"\bprojects\x18\x01 \x03(\v2\x10.project.ProjectR\bprojects\"4\n" +
	"\x13ProjectBoardRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"W\n" +
	"\x14ProjectBoardResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12)\n" +
	"\acolumns\x18\x02 \x03(\v2\x0f.project.ColumnR\acolumns\"5\n" +
	"\x14TaskBlueprintRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\xb2\x02\n" +
	"\x15TaskBlueprintResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x123\n" +
	"\vtag_options\x18\x03 \x03(\v2\x12.project.TagOptionR\n" +
	"tagOptions\x12<\n" +
	"\x0ecolumn_options\x18\x04 \x03(\v2\x15.project.ColumnOptionR\rcolumnOptions\x12B\n" +
	"\x10priority_options\x18\x05 \x03(\v2\x17.project.PriorityOptionR\x0fpriorityOptions\x12*\n" +
	"\x11current_date_time\x18\x06 \x01(\tR\x0fcurrentDateTime\"E\n" +
	"\tTagOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"H\n" +
	"\fColumnOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\",\n" +
	"\x0ePriorityOption\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\tR\bpriority\"\xf1\x01\n" +
	"\x11CreateTaskRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tcolumn_id\x18\x02 \x01(\tR\bcolumnId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bdeadline\x18\x06 \x01(\tR\bdeadline\x12\x1a\n" +
	"\bpriority\x18\a \x01(\tR\bpriority\x12\x17\n" +
	"\atag_ids\x18\b \x03(\tR\x06tagIds\"\xe3\x01\n" +
	"\x12CreateTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x12\x14\n" +
	"\x05order\x18\x04 \x01(\tR\x05order\x12\x1b\n" +
	"\tcolumn_id\x18\x05 \x01(\tR\bcolumnId\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1a\n" +
	"\bdeadline\x18\a \x01(\tR\bdeadline\x12 \n" +
	"\x04tags\x18\b \x03(\v2\f.project.TagR\x04tags\"H\n" +
	"\x13CreateColumnRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"l\n" +
	"\x14CreateColumnResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition2\xa2\x03\n" +
	"\x12ProjectGrpcService\x12N\n" +
	"\x0fGetUserProjects\x12\x1c.project.UserProjectsRequest\x1a\x1d.project.UserProjectsResponse\x12N\n" +
	"\x0fGetProjectBoard\x12\x1c.project.ProjectBoardRequest\x1a\x1d.project.ProjectBoardResponse\x12X\n" +
	"\x17GetProjectTaskBlueprint\x12\x1d.project.TaskBlueprintRequest\x1a\x1e.project.TaskBlueprintResponse\x12E\n" +
	"\n" +
	"CreateTask\x12\x1a.project.CreateTaskRequest\x1a\x1b.project.CreateTaskResponse\x12K\n" +
	"\fCreateColumn\x12\x1c.project.CreateColumnRequest\x1a\x1d.project.CreateColumnResponseBJ\n" +
	"\x1dhelper.project.planner_helperP\x01Z'github.com/dragonfarm/SoloPlanner/protob\x06proto3"

var (
	file_project_proto_rawDescOnce sync.Once
	file_project_proto_rawDescData []byte
)

func file_project_proto_rawDescGZIP() []byte {
	file_project_proto_rawDescOnce.Do(func() {
		file_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_proto_rawDesc), len(file_project_proto_rawDesc)))
	})
	return file_project_proto_rawDescData
}

var file_project_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_project_proto_goTypes = []any{
	(*Project)(nil),               // 0: project.Project
	(*Tag)(nil),                   // 1: project.Tag
	(*Task)(nil),                  // 2: project.Task
	(*Column)(nil),                // 3: project.Column
	(*UserProjectsRequest)(nil),   // 4: project.UserProjectsRequest
	(*UserProjectsResponse)(nil),  // 5: project.UserProjectsResponse
	(*ProjectBoardRequest)(nil),   // 6: project.ProjectBoardRequest
	(*ProjectBoardResponse)(nil),  // 7: project.ProjectBoardResponse
	(*TaskBlueprintRequest)(nil),  // 8: project.TaskBlueprintRequest
	(*TaskBlueprintResponse)(nil), // 9: project.TaskBlueprintResponse
	(*TagOption)(nil),             // 10: project.TagOption
	(*ColumnOption)(nil),          // 11: project.ColumnOption
	(*PriorityOption)(nil),        // 12: project.PriorityOption
	(*CreateTaskRequest)(nil),     // 13: project.CreateTaskRequest
	(*CreateTaskResponse)(nil),    // 14: project.CreateTaskResponse
	(*CreateColumnRequest)(nil),   // 15: project.CreateColumnRequest
	(*CreateColumnResponse)(nil),  // 16: project.CreateColumnResponse
}
var file_project_proto_depIdxs = []int32{
	1,  // 0: project.Task.tags:type_name -> project.Tag
	2,  // 1: project.Column.tasks:type_name -> project.Task
	0,  // 2: project.UserProjectsResponse.projects:type_name -> project.Project
	3,  // 3: project.ProjectBoardResponse.columns:type_name -> project.Column
	10, // 4: project.TaskBlueprintResponse.tag_options:type_name -> project.TagOption
	11, // 5: project.TaskBlueprintResponse.column_options:type_name -> project.ColumnOption
	12, // 6: project.TaskBlueprintResponse.priority_options:type_name -> project.PriorityOption
	1,  // 7: project.CreateTaskResponse.tags:type_name -> project.Tag
	4,  // 8: project.ProjectGrpcService.GetUserProjects:input_type -> project.UserProjectsRequest
	6,  // 9: project.ProjectGrpcService.GetProjectBoard:input_type -> project.ProjectBoardRequest
	8,  // 10: project.ProjectGrpcService.GetProjectTaskBlueprint:input_type -> project.TaskBlueprintRequest
	13, // 11: project.ProjectGrpcService.CreateTask:input_type -> project.CreateTaskRequest
	15, // 12: project.ProjectGrpcService.CreateColumn:input_type -> project.CreateColumnRequest
	5,  // 13: project.ProjectGrpcService.GetUserProjects:output_type -> project.UserProjectsResponse
	7,  // 14: project.ProjectGrpcService.GetProjectBoard:output_type -> project.ProjectBoardResponse
	9,  // 15: project.ProjectGrpcService.GetProjectTaskBlueprint:output_type -> project.TaskBlueprintResponse
	14, // 16: project.ProjectGrpcService.CreateTask:output_type -> project.CreateTaskResponse
	16, // 17: project.ProjectGrpcService.CreateColumn:output_type -> project.CreateColumnResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_project_proto_init() }
func file_project_proto_init() {
	if File_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_proto_rawDesc), len(file_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_project_proto_goTypes,
		DependencyIndexes: file_project_proto_depIdxs,
		MessageInfos:      file_project_proto_msgTypes,
	}.Build()
	File_project_proto = out.File
	file_project_proto_goTypes = nil
	file_project_proto_depIdxs = nil
}
